"""add player_heatmap_positions

Revision ID: 767fab27baed
Revises: 
Create Date: 2026-03-27 16:14:17.514020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '767fab27baed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_backup')
    op.alter_column('player_stats', 'player_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('player_stats', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('player_stats', 'matches_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'matches_started',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'matches_subbed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'assists',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_scored',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_missed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'g_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'a_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'rating',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'clean_sheets',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'clean_sheets_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'saves',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'save_percentage',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals_against',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals_against_per90',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_saved',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_conceded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('player_stats_player_id_season_key'), 'player_stats', type_='unique')
    op.create_index('idx_player_stats_expires', 'player_stats', ['expires_at'], unique=False)
    op.create_unique_constraint('uq_player_season', 'player_stats', ['player_id', 'season'])
    op.alter_column('player_stats_by_competition', 'player_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('player_stats_by_competition', 'matches_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'matches_started',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'matches_subbed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'goals',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'assists',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'g_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'a_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'rating',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'nationality',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'Poland'::character varying"))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_players_name'), table_name='players')
    op.drop_index(op.f('idx_players_team'), table_name='players')
    op.drop_constraint(op.f('players_rapidapi_id_key'), 'players', type_='unique')
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_rapidapi_id'), 'players', ['rapidapi_id'], unique=True)
    op.create_index(op.f('ix_players_team'), 'players', ['team'], unique=False)
    op.alter_column('sync_state', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'2025/26'::character varying"))
    op.alter_column('sync_state', 'matches_synced',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('synced_matches', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synced_matches', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_state', 'matches_synced',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_state', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'2025/26'::character varying"))
    op.drop_index(op.f('ix_players_team'), table_name='players')
    op.drop_index(op.f('ix_players_rapidapi_id'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.create_unique_constraint(op.f('players_rapidapi_id_key'), 'players', ['rapidapi_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_players_team'), 'players', ['team'], unique=False)
    op.create_index(op.f('idx_players_name'), 'players', ['name'], unique=False)
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'nationality',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'Poland'::character varying"))
    op.alter_column('player_stats_by_competition', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('player_stats_by_competition', 'rating',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'a_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'g_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'assists',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'goals',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'matches_subbed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'matches_started',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'matches_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats_by_competition', 'player_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('uq_player_season', 'player_stats', type_='unique')
    op.drop_index('idx_player_stats_expires', table_name='player_stats')
    op.create_unique_constraint(op.f('player_stats_player_id_season_key'), 'player_stats', ['player_id', 'season'], postgresql_nulls_not_distinct=False)
    op.alter_column('player_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('player_stats', 'penalties_conceded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_saved',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals_against_per90',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals_against',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'save_percentage',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'saves',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'clean_sheets_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'clean_sheets',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'rating',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'a_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'g_per90',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_missed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'penalties_scored',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'assists',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'goals',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'matches_subbed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'matches_started',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'matches_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_stats', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('player_stats', 'player_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_table('players_backup',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rapidapi_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('league', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
